---
- name: setup webserver
  hosts: webservers
  become: true
  tasks:
    - name: httpd installed
      ansible.builtin.yum:
        name: httpd
        state: latest
    - name: custom index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          This is Webserver running on httpd          
    - name: httpd service enabled
      ansible.builtin.service:
        name: httpd
        enabled: true
        state: started
    - name: open firewall
      ansible.posix.firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true